service:
  name: orders-rest-api

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-deployment-bucket
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x 
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  profile: serverless-admin
  deploymentBucket:
    name: orders-rest-api
    serverSideEncryption: AES256
  environment:
    ORDERS_TABLE_NAME: ${self:custom.OrdersTable.name} 
    ORDERS_BUCKET_NAME: ${self:custom.OrdersBucket.name}
  iam: 
   role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:ap-south-1:670022476151:table/Orders-dev 
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: arn:aws:s3:::${self:custom.OrdersBucket.name}/* 

resources:
  Resources:
    OrdersTable: ${file(infra/resources/dynamodb.yml):OrdersTable}
    OrdersBucket: ${file(infra/resources/s3.yml):OrdersBucket}
    OrdersBucketPolicy: ${file(infra/resources/s3.yml):OrdersBucketPolicy}
    
functions:
  orderHealthCheck:
    handler: app/handlers/health.handler
    events:
      - http:
          method: GET
          path: /health
          cors: true
  createorder:
    handler: app/handlers/createOrder.handler
    events:
      - http:
          method: POST
          path: /order
          cors: true 
  getorder:
    handler: app/handlers/getOrder.handler
    events:
      - http:
          method: GET
          path: /order/{OrderId}
          cors: true
  getorderbybrand:
    handler: app/handlers/getOrdersByBrand.handler
    events:
      - http:
          method: GET
          path: /order/brand/{BrandId}
          cors: true
  getorderbycustomer:
    handler: app/handlers/getOrdersByCustomer.handler
    events:
      - http:
          method: GET
          path: /order/customer/{CustomerId}
          cors: true
  patchOrderStatus:
    handler: app/handlers/updateOrderStatus.handler
    events:
      - http:
          path: /order/updatStatus
          method: patch
          cors: true

custom:
  stage: dev 
  webpack: 
    keepOutputDirectory: true
    includeModules:
      packagePath: './package.json'
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file 
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore 
  domains: 
    dev: api.migobucks.com
    # prod: api.migobucks.com 
  OrdersTable:
    name: !Ref OrdersTable
    arn: !GetAtt OrdersTable.Arn 
  OrdersBucket:
    name: orders-rest-api-${self:provider.stage} 
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: 'orders'
    stage: dev 
    createRoute53Record: true 
  bundle:
    linting: false 