OrdersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Orders-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: OrderId
        AttributeType: S
      - AttributeName: OrderStatus
        AttributeType: S
      - AttributeName: BrandId
        AttributeType: S
      - AttributeName: ProductId
        AttributeType: S
      - AttributeName: CustomerId
        AttributeType: S
      - AttributeName: CreatedDate
        AttributeType: S
    KeySchema:
      - AttributeName: OrderId
        KeyType: HASH
      - AttributeName: CustomerId
        KeyType: RANGE
    LocalSecondaryIndexes:
      - IndexName: OrderIdAndOrderStatus
        KeySchema:
          - AttributeName: OrderId
            KeyType: HASH
          - AttributeName: OrderStatus
            KeyType: RANGE 
        Projection:
            ProjectionType: ALL 
      - IndexName: OrderIdAndProductId
        KeySchema:
          - AttributeName: OrderId
            KeyType: HASH
          - AttributeName: ProductId
            KeyType: RANGE 
        Projection:
            ProjectionType: ALL 
      - IndexName: OrderIdAndCreatedDate
        KeySchema:
          - AttributeName: OrderId
            KeyType: HASH
          - AttributeName: CreatedDate
            KeyType: RANGE 
        Projection:
            ProjectionType: ALL  
      - IndexName: OrderIdAndBrandId
        KeySchema:
          - AttributeName: OrderId
            KeyType: HASH
          - AttributeName: BrandId
            KeyType: RANGE 
        Projection:
            ProjectionType: ALL 
      - IndexName: OrderIdAndCustomerId
        KeySchema:
          - AttributeName: OrderId
            KeyType: HASH
          - AttributeName: CustomerId
            KeyType: RANGE 
        Projection:
            ProjectionType: ALL 