OrdersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Orders-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: OrderId
        AttributeType: S
      - AttributeName: OrderStatus
        AttributeType: S
      - AttributeName: BrandId
        AttributeType: S
      - AttributeName: ProductId
        AttributeType: S
      - AttributeName: CustomerId
        AttributeType: S
      - AttributeName: CreatedDate
        AttributeType: S
      - AttributeName: UserType
        AttributeType: S
    KeySchema:
      - AttributeName: CustomerId
        KeyType: HASH
      - AttributeName: OrderId
        KeyType: RANGE
    LocalSecondaryIndexes:
      - IndexName: OrderIdAndOrderStatus
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: OrderStatus
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndProductId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: ProductId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndCreatedDate
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: CreatedDate
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndBrandId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: BrandId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: UserTypeAndCustomerId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: UserType
            KeyType: RANGE
        Projection:
          ProjectionType: ALL

ReturnsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Returns-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: ReturnOrderId
        AttributeType: S
      - AttributeName: OrderStatus
        AttributeType: S
      - AttributeName: BrandId
        AttributeType: S
      - AttributeName: ProductId
        AttributeType: S
      - AttributeName: CustomerId
        AttributeType: S
      - AttributeName: ReturnDate
        AttributeType: S
    KeySchema:
      - AttributeName: CustomerId
        KeyType: HASH
      - AttributeName: ReturnOrderId
        KeyType: RANGE
    LocalSecondaryIndexes:
      - IndexName: OrderIdAndOrderStatus
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: OrderStatus
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndProductId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: ProductId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndCreatedDate
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: ReturnDate
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndBrandId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: BrandId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndCustomerId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: ReturnOrderId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
CancelledTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Cancelled-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: OrderId
        AttributeType: S
      - AttributeName: OrderStatus
        AttributeType: S
      - AttributeName: BrandId
        AttributeType: S
      - AttributeName: ProductId
        AttributeType: S
      - AttributeName: CustomerId
        AttributeType: S
      - AttributeName: CancelledDate
        AttributeType: S
    KeySchema:
      - AttributeName: CustomerId
        KeyType: HASH
      - AttributeName: OrderId
        KeyType: RANGE
    LocalSecondaryIndexes:
      - IndexName: OrderIdAndOrderStatus
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: OrderStatus
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndProductId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: ProductId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndCancelledDate
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: CancelledDate
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndBrandId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: BrandId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OrderIdAndCustomerId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: OrderId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
CartTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Cart-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: CartId
        AttributeType: S
      - AttributeName: ProductId
        AttributeType: S
      - AttributeName: CustomerId
        AttributeType: S
      - AttributeName: CreatedDate
        AttributeType: S
      - AttributeName: BrandId
        AttributeType: S
    KeySchema:
      - AttributeName: CustomerId
        KeyType: HASH
      - AttributeName: CartId
        KeyType: RANGE
    LocalSecondaryIndexes:
      - IndexName: CustomerIdAndProductId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: ProductId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: CustomerIdAndCreatedDate
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: CreatedDate
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: CustomerIdAndBrandId
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: BrandId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
