OrdersBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.OrdersBucket.name}
    LifecycleConfiguration:
      Rules:
        - Id: ExpirePictures
          Status: Enabled
          ExpirationInDays: 1

OrdersBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref OrdersBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.OrdersBucket.name}/*